### ISSUE TITLE
Viewer chapter loader on `Windows`

### ISSUE THREAD

**Issue by kondanta** [Egomination/MangApplizer-Beta#29]
![](https://image.ibb.co/egCqVR/Screenshot_311.png)

- It seems to be broken

**Comment by sasalx** [comment]
So much info to work with I am amazed. Also you know why that happens. It's an ordering problem because of the downloading script.

**Comment by kondanta** [comment]
The thing is, it does it only on my windows machine. In linux, everything is good. That's why I cannot add more information about this issue.

**Comment by sasalx** [comment]
Let's start with basics. Which source? Which manga? And calling it again its about the downloading script you wrote. Because of that don't know why it does that.

**Comment by kondanta** [comment]
Like I said, it does it only in `windows` and source free. Also all of the mangas. 
And let me clarify that it's not about the script that I wrote. I use f*cking regex to get chapter numbers. #26

**Comment by sasalx** [comment]
Language please.

At least tell me the manga names and their source so that I too can try it. I hope you are not expecting to solve a problem with no info whatsoever.

**Comment by sasalx** [comment]
So I am doing the test you should have. *Oh well*

**Test Results**

OS: `Windows 10`

- [x] Source: Kissmanga Manga: Kingdom Chapters: 1, 2, 10, 11, 12, 20, 21, 111
- [x] Source: Kissmanga Manga: Shokugeki no Souma Chapters: 1, 2, 10, 11, 12, 20, 21, 111
- [ ] Source: Lhscan Manga: Nejimage Factor Chapters: 1, 10, 11, 12, 2, 20, 21, 5.5
- [ ] Source: Lhscan Manga: Tsumi to Kai Chapters: 1, 10, 11, 17, 2

So seems like lhscan causing the problem. Probably a problem with regex. Also since kissmanga has no problem the issue is not about viewer for sure.
> Source free

![](http://31.media.tumblr.com/eb75e9e1d9588181edaf55abbcd01c1b/tumblr_n8rsyrVe981rb06tgo1_250.gif)

Note: I had to read two bad mangas because of you...

**Comment by sasalx** [comment]
Fixed with #31.
